#!/usr/bin/env bash
set -euo pipefail

VERSION="${1:-0.1.0}"
NAME="Wisp"
BUNDLE_ID="com.sulemaanhamza.wisp"
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
BUILD_DIR="$ROOT/build"
APP_DIR="$BUILD_DIR/$NAME.app"

# Universal (arm64 + x86_64) so Intel Macs can run Wisp too.
#
# Not `swift build --arch arm64 --arch x86_64`: that path needs Xcode's
# xcbuild, and this project is meant to build with bare Command Line
# Tools. Two single-arch builds plus lipo gets the same fat binary with
# nothing but the Swift toolchain.
echo "Building $NAME $VERSION (release, universal)..."
ARCH_DIR="$ROOT/.build-universal"
SLICES=()
for TRIPLE in arm64-apple-macosx13.0 x86_64-apple-macosx13.0; do
    echo "  - $TRIPLE"
    swift build -c release \
        --package-path "$ROOT" \
        --triple "$TRIPLE" \
        --scratch-path "$ARCH_DIR/$TRIPLE"
    # Ask SwiftPM where it put the binary rather than assuming the
    # layout of its scratch directory.
    BIN_DIR="$(swift build -c release \
        --package-path "$ROOT" \
        --triple "$TRIPLE" \
        --scratch-path "$ARCH_DIR/$TRIPLE" \
        --show-bin-path)"
    SLICE="$BIN_DIR/$NAME"
    [[ -x "$SLICE" ]] || { echo "Error: build did not produce $SLICE" >&2; exit 1; }
    SLICES+=("$SLICE")
done

BINARY="$ARCH_DIR/$NAME"
lipo -create "${SLICES[@]}" -output "$BINARY"
echo "  = $(lipo -info "$BINARY")"

rm -rf "$APP_DIR"
mkdir -p "$APP_DIR/Contents/MacOS"
mkdir -p "$APP_DIR/Contents/Resources"

cp "$BINARY" "$APP_DIR/Contents/MacOS/$NAME"

# Copy the app icon (generated by scripts/generate-icon.swift)
ICON_SRC="$ROOT/scripts/AppIcon.icns"
if [[ -f "$ICON_SRC" ]]; then
    cp "$ICON_SRC" "$APP_DIR/Contents/Resources/AppIcon.icns"
else
    echo "Warning: $ICON_SRC missing — bundle will have no icon" >&2
fi

cat > "$APP_DIR/Contents/Info.plist" <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>CFBundleDevelopmentRegion</key>
    <string>en</string>
    <key>CFBundleExecutable</key>
    <string>$NAME</string>
    <key>CFBundleIconFile</key>
    <string>AppIcon</string>
    <key>CFBundleIdentifier</key>
    <string>$BUNDLE_ID</string>
    <key>CFBundleInfoDictionaryVersion</key>
    <string>6.0</string>
    <key>CFBundleName</key>
    <string>$NAME</string>
    <key>CFBundleDisplayName</key>
    <string>$NAME</string>
    <key>CFBundlePackageType</key>
    <string>APPL</string>
    <key>CFBundleShortVersionString</key>
    <string>$VERSION</string>
    <key>CFBundleVersion</key>
    <string>$VERSION</string>
    <key>LSMinimumSystemVersion</key>
    <string>13.0</string>
    <key>LSUIElement</key>
    <true/>
    <key>NSHighResolutionCapable</key>
    <true/>
</dict>
</plist>
EOF

# Ad-hoc sign so the binary can load on Apple Silicon. Doesn't satisfy
# Gatekeeper (no Developer ID), but without this users see "killed: 9".
codesign --sign - --force --deep "$APP_DIR" >/dev/null 2>&1

echo "Built $APP_DIR"
